USE [master]
GO

/****** Object:  Database [StudentAdminPortalDb]    Script Date: 18-11-2022 14:14:48 ******/
CREATE DATABASE [StudentAdminPortalDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudentAdminPortalDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\StudentAdminPortalDb.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StudentAdminPortalDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\StudentAdminPortalDb_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StudentAdminPortalDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentAdminPortalDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentAdminPortalDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [StudentAdminPortalDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentAdminPortalDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentAdminPortalDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StudentAdminPortalDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentAdminPortalDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [StudentAdminPortalDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StudentAdminPortalDb] SET  MULTI_USER 
GO

ALTER DATABASE [StudentAdminPortalDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentAdminPortalDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentAdminPortalDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentAdminPortalDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [StudentAdminPortalDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentAdminPortalDb] SET  READ_WRITE 
GO


